version: "3"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
    - ./data:/data/db
    ports:
    - 27017:27017

  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGO_USERNAME=
      - MONGO_PASSWORD=
      - MONGO_PORT=27017
      - MONGO_DB=