version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/share/elasticsearch/data
    healthcheck:
      test: curl -f http://localhost:9200 || exit 1
      interval: 2s
      timeout: 5s
      retries: 30

  # app:
  #   build: .
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGO_HOST=localhost
  #     - MONGO_PORT=27017
  #     - MONGO_DB=feeds
  #   links:
  #     - "mongodb"
  #     - "elasticsearch"
  #   depends_on:
  #     elasticsearch:
  #       condition: service_health
